#!/usr/bin/env bash
# This script creates an RSA key pair with the specified parameters

# Set the key name and passphrase
KEY_NAME="school"
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b 4096 -N "$PASSPHRASE" -f "$KEY_NAME"
