#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5498-web
    bind *:80
    mode http
    balance roundrobin
    server 5498-web-01 3.85.134.255:80 check
    server 5498-web-02 18.207.124.61:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
